# Generated by Django 3.1.7 on 2021-03-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20210301_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
